version: '3.8'
services:
  hr-tool:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4201:4200"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
